config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  post '/clock_in', to: 'clock_events#clock_in'
  post '/clock_out', to: 'clock_events#clock_out'
  resources :clock_events, only: %i(index edit destroy)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clock_event.rb
class ClockEvent < ApplicationRecord
  belongs_to :user

  scope :latest, -> { order(created_at: :desc) }
  
  def clocked_in?
    !clock_out_at
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :clock_events

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :warning, :danger, :info, :data
end

app/controllers/clock_events_controller.rb
class ClockEventsController < ApplicationController
  before_action :handle_login, only: %i(clock_in clock_out)

  # GET /clock_events
  def index
    @clock_events = ClockEvent.includes(:user).latest.page(params[:page])
  end

  # POST /clock_in
  def clock_in
    @clock_event = @user.clock_events.new(clock_in_at: Time.current)

    if !clock_in_params[:clock_in_again] && @user.clock_events.latest.first&.clocked_in?
      return redirect_to root_path, { 
        danger: "You're already clocked in. Please confirm that you want to clock in again.",
        data: { is_clocked_in_already: true },
      }
    end

    if @clock_event.save
      redirect_to root_path, success: "You're clocked in."
    else
      redirect_to root_path, danger: "Error creating Clock Event."
    end
  end

  # PATCH/PUT /clock_out
  def clock_out
    @clock_event = @user.clock_events.latest.first

    if @clock_event&.clocked_in? && @clock_event&.update(clock_out_at: Time.current)
      redirect_to root_path, success: "You've been clocked out."
    else
      message = @clock_event&.clocked_in? ? 
        "Error updating Clock Event." :
        "The last Clock Event has already been clocked out."
      redirect_to root_path, danger: message
    end
  end

  private
  
    def handle_login
      @user = User.find_by(email: clock_in_params[:email].downcase)
      unless @user&.authenticate(clock_in_params[:password])
        redirect_to root_path, danger: "Invalid login credentials."
      end
    end

    def clock_in_params
      params.permit(:email, :password, :clock_in_again)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clock_events/index.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
  <h3>Clock Events</h3>

  <table class="striped highlight responsive-table">
    <thead>
      <tr>
        <th>#</th>
        <th>User</th>
        <th>Clock in at</th>
        <th>Clock out at</th>
      </tr>
    </thead>

    <tbody>
      <% @clock_events.each do |clock_event| %>
        <tr id=<%= clock_event.id %>>
          <td class="number"><%= clock_event.id %></td>
          <td class="full_name"><%= clock_event.user.full_name %></td>
          <td class="clock_in_at"><%= clock_event.clock_in_at %></td>
          <td class="clock_out_at"><%= clock_event.clock_out_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @clock_events %>
</div>

app/views/home/index.html.erb
<div class="container" style="max-width: 500px">
    <h3>Clock In/Out</h3>
    <br>

    <div class="card-panel">
        <%= form_tag(clock_in_path, method: :post) do %>
            <!-- NOTE: The authenticity_token is added here because sometimes the "Clock Out" submit button fails -->
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

            <%= label_tag(:email, "Email:") %>
            <%= text_field_tag(:email) %>
            <br>

            <%= label_tag(:password, "Password:") %>
            <%= password_field_tag(:password) %>
            <br>

            <% if flash[:data].to_h.dig('is_clocked_in_already') %>
                <br>
                <label name="clock_in_again">
                    <input type="checkbox" name="clock_in_again" id="clock_in_again" value="1">
                    <span>Confirm clock in</span>
                </label>
                <br>
            <% end %>

            <br>

            <%= submit_tag("Clock In", class: "btn white-text left green") %>
            <%= submit_tag("Clock Out", class: "btn white-text right red", formaction: clock_out_path) %>

            <br>
            <br>

        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Himama Coding Challenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

     <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-fixed">
      <nav>
        <div class="nav-wrapper teal">
          <a href="<%= root_path %>" class="brand-logo">&nbsp; HiMama</a>
          <ul class="right hide-on-med-and-down">
            <li><%= link_to 'Clock In/Out', :root %></li>
            <li><%= link_to 'Clock Events', :clock_events %></li>
          </ul>
        </div>
      </nav>
    </div>

    <% flash.each do |key, value| %>
      <% next unless %w(success warning danger info).include?(key) %>
      <% colors = {"success" => :green, "warning" => :yellow, "danger" => :red, "info" => :blue} %>
      <div class="container center" style="max-width: 600px">
        <div class="card <%= colors[key]%> lighten-5">
        <h5 class="<%= colors[key]%>-text text-darken-4" style="padding: .5em"><%= value %></h5>
        </div>
        <br>
      </div>
    <% end %>

   

    <main>
      <%= yield %>
    </main>

    <footer class="page-footer teal">
        <div class="container">
          © 2019 Copyright Greg Answer
          <a class="grey-text text-lighten-4 right" href="https://github.com/greganswer/himama_coding_challenge"> 
            GitHub Repo
          </a>
        </div>
        <br>
    </footer>
  </body>
</html>